### PR TITLE
Add custom_fields in logging configuration

### PR DESCRIPTION
**Pull request by muffl0n**
Instead of adding custom fields in the code it would be neat to have the possibility to add fields in the logging configuration when adding the handler:

```
                'gelf': {
                    'level': 'DEBUG',
                    'class': 'graypy.GELFHandler',
                    'formatter': 'standard',
                    'host': 'mylogserver',
                    'port': 12201,
                    'custom_fields': {'app': 'example'}
                }
```

This PR adds the parameter "custom_fields" to GELFHandler.**init**(). Adding of the fields is done at the end of make_message_dict() with calling add_custom_fields(). I'm not quite happy about this way cause this method is nearly the same as add_extra_fields(). I would try to make a better solution if needed.

### CODE REVIEW

**Comment by muffl0n** [comment]
I moved the "skip_list" to module level as "MESSAGE_FIELD_SKIP_LIST" so that "add_custom_fields()" and "add_extra_fields()" both use the same list.

**Comment by severb** [comment]
I wonder if this should happen only in the `else` clause of `if extra_fields:`. IIRC  if `extra_fields` is set, all the fields are included, rendering `custom_fields` redundant.

**Comment by muffl0n** [comment]
extra_fields are set in the code, with LoggerAppender, for example. The custom_fields introduced by this PR are exclusively coming from the handler's configuration.
I wanted to create a possibility to add fields without changing the code as I believe that this strictly belongs into the configuration of the logger/handler.

Maybe the name "custom_fields" isn't the best choice. [logback-gelf](https://github.com/Moocar/logback-gelf/blob/master/README.md) calls them "staticFields", for example.

**Comment by severb** [comment]
Oh, I see; what's wrong with using a `LoggerAdapter`, except for the extra boilerplate?

**Comment by muffl0n** [comment]
I think it's inconvenient that you have to change the code to change the fields you are feeding via GELF.
Especially because other's, like the mentioned logback-gelf, have some sort of facility for that.

**Comment by severb** [comment]
While the logging API has its quirks I don't like adding another way to set static fields. I think you can implement your own function that gets the same arguments as `GELFHandler` plus `custom_fields` and does the `LoggerAdapter` wrapping automatically; adding similar behaviour in this library doesn't feel right to me.

**Comment by muffl0n** [comment]
I totally understand your point. But it also doesn't feel right to me to add boilerplate code to applications just to add fields for Logging via GELF. Adding an additional handler should in no way influence the code you have. In my opinion this includes the mentioned "custom_fields" or whatever one would name them.

https://github.com/t0xa/gelfj, http://logging.paluch.biz/examples/jul.html, https://github.com/Graylog2/log4j2-gelf as well as the already mentioned https://github.com/Moocar/logback-gelf/ all have the same kind of facility for that, called "additionalFields" or "staticFields". So the idea doesn't seem to be so unique.

**Comment by tusharmakkar08** [comment]
Closing it since it's not active.

**Pull request closed without merging**
