### PR TITLE
add ability to apply a logger.Formatter to a GLEF logs `short_message` and `long_message`

### PR DESCRIPTION
**Pull request by nklapste**
Adds the ability to specify a python `logging.Formatter` within the initialization of a `BaseGELFHandler` or its children. This allows the  `logging.Formatter` to be applied to the GELF log's `short_message` and `long_message`. 

Small refactoring and modernization of the python codebase was also done.

### CODE REVIEW

**Comment by severb** [comment]
Nathan, can you please rebase on top of the latest master? I already merged the cleanup part.

**Comment by nklapste** [comment]
> 
> 
> Nathan, can you please rebase on top of the latest master? I already merged the cleanup part.

Sure I can start some updates on this branch. It should be done by the end of this week.

**Comment by nklapste** [comment]
I ended up changing the way to set the formatter to use a `setFormatter` method in the base class `BaseGELFHandler`. This seems cleaner and resembles how other python logging handlers work.

Please review and see if this specification is preferable.

It may be beneficial in the future to make `BaseGELFHandler` a subclass of `logging.Handler` as to fully encompass all python logging handler behavior.

**Comment by nklapste** [comment]
Also note this does not raise the version number of `graypy`. I would recommend `v0.4.0`.

**Comment by nklapste** [comment]
@severb any ETA on review and merging?

**Comment by severb** [comment]
Sorry for the lag on my side. Thanks for the patch!

**Pull request merged**
