### PR TITLE
Feature/improved structuring

### PR DESCRIPTION
**Pull request by nklapste**
Another restructuring of graypy focusing on making the construction of handlers more straight forward. Along with improving testing coverage for sanity checking.

**Note:** Due to the changes in naming and separation of handlers these changes are backwards breaking.

### Work in progress: 
* added a stub within the `.travis.yml` for adding automatic deployment to pypi

### Features:
* Detailed docstrings noting the usage of components
* Typing noted in the docstrings
* Configuration notes are removed from the `README.rst` duplicates the docstrings (maybe we should use read the docs or somesort?)
* Improved testing by using a docker container running graylog to send test messages to
* `GELFHTTPHandler` handler has been added
* GELF encoding is now contained within `BaseGELFHandler`
* TCP and TLS handlers are now separated to avoid confusion

### CODE REVIEW

**Comment by severb** [comment]
This PR looks fantastic, is it ready for master? If so, please land and bump the version to `0.4.0`.

**Comment by nklapste** [comment]
> 
> 
> This PR looks fantastic, is it ready for master? If so, please land and bump the version to `0.4.0`.

I would have to look over my work on this branch again, it has been a long time since I looked back at this branch. I should be able to re-review sometime this week.

I do believe some of the API for initializing some of these classes did in fact change. I would recommended bumping to a `1.X.X` build if we merge and update.

**Comment by nklapste** [comment]
One thing to note was the the creation of TCP and TLS has been separated into different classes `GELFTCPHandler` and `GELFTLSHandler` . This was to remove the usage of optional arguments.

**Comment by severb** [comment]
You're right—we should bump the major component if it breaks backward compatibility.

**Comment by nklapste** [comment]
Seems that the tests for py3.4 are failing to package version conflicts. I'll look into it tonight.

**Comment by nklapste** [comment]
@severb  everything should be good to go. Do you want me to merge then bump the version to `1.0.0` and tag?

**Pull request merged**
